### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by tatat** [japan-d2/js-schema#1]
`Pure<typeof someSchema>` causes `Type instantiation is excessively deep and possibly infinite.` since 0.0.13

**Comment by uneco** [comment]
fixes in https://github.com/japan-d2/js-schema/commit/759a6e49a61ba7d8b4b097896aae3eb62e70ec06

**Comment by tatat** [comment]
because of different versions are in combination, the problem occurred.
